[tool.poetry]
name = "refactornci"
version = "0.1.0"
description = ""
authors = ["10Hr <10hourmail@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flake8 = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
