name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      if: runner.os == 'Linux' || runner.os == 'macOS'

    - name: Install project dependencies, including Flake8
      run: |
        poetry install
      working-directory: ./refactorNCI

    - name: Run Flake8
      run: |
        poetry update flake8
        poetry self update
        poetry run flake8
      working-directory: ./refactorNCI

    - name: Run tests and generate code coverage report
      run: |
        poetry run pytest --cov=./refactorNCI
      working-directory: ./refactorNCI

    - name: Upload code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./refactorNCI/htmlcov
