name: Python CI

on:
  push:
    branches:
      - main  # You can adjust this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you want to use

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      if: runner.os == 'Linux' || runner.os == 'macOS'

    - name: Install project dependencies
      run: |
        poetry install
      working-directory: path/to/your/project  # Set the path to your project

    - name: Run Flake8
      run: |
        poetry run flake8
      working-directory: path/to/your/project  # Set the path to your project

    - name: Run tests and generate code coverage report
      run: |
        poetry run pytest --cov=path/to/your/project
      working-directory: path/to/your/project  # Set the path to your project

    - name: Upload code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: path/to/your/project/htmlcov  # Set the path to your coverage report
